package fabricate

// A Config defines certain behaviors of a Fabricator
//
// DefaultGeneratorsEnabled: Whether default generators will be used for literals
// DefaultSliceLength: Default length of generated slices
// DefaultMapSize: Default size of generated maps
// DefaultStringLength: Default length of generated strings
// GeneratePtrs: Whether ptrs should be generated by default
// MaxRecursiveStructDepth: When a struct has a field that's a ptr to its own type, how deep it should generate
type Config struct {
	DefaultGeneratorsEnabled bool
	DefaultSliceLength       int
	DefaultMapSize           int
	DefaultStringLength      int
	GeneratePtrs             bool
	MaxRecursiveStructDepth  int
}

func defaultConfig() *Config {
	return &Config{
		DefaultGeneratorsEnabled: true,
		DefaultMapSize:           3,
		DefaultSliceLength:       3,
		DefaultStringLength:      8,
		GeneratePtrs:             true,
		MaxRecursiveStructDepth:  2,
	}
}
